{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Architect API",
    "description" : "API Backend for Architect Website",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "http://localhost:5678/api/"
  } ],
  "paths" : {
    "/users/login" : {
      "post" : {
        "summary" : "Log In the user.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/users_login_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Connected",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          },
          "404" : {
            "description" : "User not found"
          },
          "401" : {
            "description" : "Not Authorized"
          }
        }
      }
    },
    "/categories" : {
      "get" : {
        "summary" : "Returns all categories",
        "responses" : {
          "200" : {
            "description" : "Returns an array of all categories",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/inline_response_200_1"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Unexpected Error"
          }
        }
      }
    },
    "/works" : {
      "get" : {
        "summary" : "Returns all works",
        "responses" : {
          "200" : {
            "description" : "Returns an array of all works",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/inline_response_200_2"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Unexpected Error"
          }
        }
      },
      "post" : {
        "summary" : "Send a new Work",
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "$ref" : "#/components/schemas/works_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_201"
                }
              }
            }
          },
          "500" : {
            "description" : "Unexpected Error"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "400" : {
            "description" : "Bad Request"
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    },
    "/works/{id}" : {
      "delete" : {
        "summary" : "Delete a work depending on id",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "id of work to be deleted",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Item Deleted"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "500" : {
            "description" : "Unexpected Behaviour"
          }
        },
        "security" : [ {
          "BearerAuth" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "users_login_body" : {
        "type" : "object",
        "properties" : {
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_1" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "name" : {
            "type" : "string",
            "example" : "Objets"
          }
        }
      },
      "inline_response_201" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "title" : {
            "type" : "string"
          },
          "imageUrl" : {
            "type" : "string"
          },
          "categoryId" : {
            "type" : "string"
          },
          "userId" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "userId" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "token" : {
            "type" : "string",
            "example" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MTg3NDkzOSwiZXhwIjoxNjUxOTYxMzM5fQ.JGN1p8YIfR-M-5eQ-Ypy6Ima5cKA4VbfL2xMr2MgHm4"
          }
        }
      },
      "inline_response_200_2" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "title" : {
            "type" : "string",
            "example" : "Abajour Tahina"
          },
          "imageUrl" : {
            "type" : "string",
            "example" : "http://localhost:5678/images/abajour-tahina1651286843956.png"
          },
          "categoryId" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "userId" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "category" : {
            "$ref" : "#/components/schemas/inline_response_200_1"
          }
        }
      },
      "works_body" : {
        "type" : "object",
        "properties" : {
          "image" : {
            "type" : "string",
            "format" : "binary"
          },
          "title" : {
            "type" : "string"
          },
          "category" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      }
    },
    "securitySchemes" : {
      "BearerAuth" : {
        "type" : "http",
        "scheme" : "bearer"
      }
    }
  }
}